[package]
name = "fracture"
version = "0.1.0"
authors = ["Yoganand <59907866+Yoganand20@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = ["router", "desktop"], optional = true }
tokio = { version = "1.52.2", features = ["full"] }
hickory-resolver = { version = "0.24", features = ["dns-over-rustls", "dns-over-https-rustls", "webpki-roots", "dns-over-quic"] }
httparse = "1.10.1"
winreg = "0.56.0"
clap = { version = "4.4", features = ["derive"] }
tracing = "0.1.44"
anyhow = "1.0.102"
tracing-subscriber = "0.3.23"
tracing-appender = "0.2.5"
chrono = "0.4.45"
rand = "0.10.1"

[[bin]]
name = "fracture-cli"
path = "src/bin/fracture-cli.rs"
required-features = ["cli"]

[features]
default = ["cli", "desktop"]
cli = []
desktop = ["dioxus/desktop"]

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
incremental = false
