/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-05-04T18:19:09.027089900+00:00
/// Collection: lucide
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/lucide/>
///
/// ```yaml
/// name: Lucide
/// author:
///   name: Lucide Contributors
///   url: https://github.com/lucide-icons/lucide
/// license:
///   title: ISC
///   spdx: ISC
///   url: https://github.com/lucide-icons/lucide/blob/main/LICENSE
/// total: 1703
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;
#[allow(non_upper_case_globals)]
pub const Minus: IconData = IconData {
    name: "lucide:minus",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
#[allow(non_upper_case_globals)]
pub const Shield: IconData = IconData {
    name: "lucide:shield",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
#[allow(non_upper_case_globals)]
pub const X: IconData = IconData {
    name: "lucide:x",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 6L6 18M6 6l12 12"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
